### ISSUE TITLE
Script fails when author name contains '<>' chars

### ISSUE THREAD

**Issue by lalloni** [NitorCreations/license-maintainer#5]
If I use:

    git config license.author "John Doe <john@doe.org>"

Then, after the initial setup of license headers (which works fine, producing a correct commit), every try to make a new commit fails saying the headers are broken in all files.

Note that if I remove the email from `license.author` using:

    git config license.author "John Doe"

Then the pre-commit hook starts working as expected.

My guess is that the author regexp built in license.pm:76 is too restrictive.

**Comment by xkr47** [comment]
Fixed in #6
